apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-project
labels:
  - pairs:
      environment: development
    includeSelectors: false
resources:
  - ../../base/hi-golang-project
  - ../../base/golang-gitops-project
patches: []


images:
  - name: hegieswe/golang-gitops-project
    newTag: "6938e6c"
