apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hegi-technicaltest-04042026
labels:
  - pairs:
      environment: development
    includeSelectors: false
resources:
  - ../../base/hello-world-service-python
  - ../../base/hello-world-service-java
patches: []


images:
  - name: hegieswe/hello-world-service-java
    newTag: "42654d0"
  - name: hegieswe/hello-world-service-python
    newTag: "8c0d73a"
