apiVersion: v1
kind: Service
metadata:
  name: hello-golang
  labels:
    app: hello-golang
spec:
  selector:
    app: hello-golang
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32020
      protocol: TCP
  type: NodePort
