apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-java
spec:
  selector:
    app: hello-world-service-java
  ports:
    - port: 8201
      targetPort: 8201
      nodePort: 31804
  type: NodePort
