apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-golang-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hi-golang-project
  template:
    metadata:
      labels:
        app: hi-golang-project
    spec:
      containers:
        - name: hi-golang-project
          image: hegieswe/hi-golang-project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10

